env:
   global:
     - CONAN_REFERENCE: "jwasm/2.12"
     - CONAN_USERNAME: "dbely"
     - CONAN_LOGIN_USERNAME: "dbely"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/dbely/conan"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
